### ISSUE TITLE
pypi

### ISSUE THREAD

**Issue by M0NsTeRRR** [napalm-automation-community/napalm-fsos#3]
Hello,

I can't find this package on pypi, I think it's not yet published on it ? (as I see, the readme mention an other plugin napalm-arubaos-switch)

Best regards,

**Comment by maxiestudies** [comment]
Hi Ludovic,

The driver is still not published because it’s still missing some core functionality, but I’m still working on it

**Comment by M0NsTeRRR** [comment]
> Hi Ludovic, The driver is still not published because it’s still missing some core functionality, but I’m still working on it
> […](#)
> On 6. May 2022, at 17:28, Ludovic Ortega ***@***.***> wrote: ﻿ Hello, I can't find this package on pypi, I think it's not yet published on it ? (as I see, the readme mention an other plugin napalm-arubaos-switch) Best regards, — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

Okay, thanks for your quick answer :)

If you need some testers I got a S3900-24T4S running last firmware :)

**Comment by M0NsTeRRR** [comment]
It seems that some products like S3900 doesn't have RPC API and FS don't plan to add it on this type of products when I emailed them.

**Comment by maxiestudies** [comment]
Yes, I’m working on a 5800 platform
